<!DOCTYPE html>
<html>
<head>
    <title>Plastic Bag Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { margin: 0; font-size: 18px; }
        .header p { margin: 5px 0; color: #666; }
        .summary-cards { display: flex; justify-content: space-between; margin-bottom: 20px; }
        .summary-card { flex: 1; margin: 0 10px; padding: 10px; border: 1px solid #ddd; text-align: center; }
        .summary-card h3 { margin: 0; font-size: 14px; color: #333; }
        .summary-card .value { font-size: 16px; font-weight: bold; color: #007bff; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f8f9fa; font-weight: bold; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .section-title { font-size: 16px; font-weight: bold; margin: 20px 0 10px 0; }
        .footer { margin-top: 20px; font-size: 10px; color: #666; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Plastic Bag Report</h1>
        <p>Period: {{ $start_date }} to {{ $end_date }}</p>
        <p>Generated on: {{ date('Y-m-d H:i:s') }}</p>
    </div>

    <!-- Summary Cards -->
    <div class="summary-cards">
        <div class="summary-card">
            <h3>Total Bags Sold</h3>
            <div class="value">{{ number_format($total_bags) }}</div>
        </div>
        <div class="summary-card">
            <h3>Total Revenue</h3>
            <div class="value">${{ number_format($total_charges, 2) }}</div>
        </div>
        <div class="summary-card">
            <h3>Total Transactions</h3>
            <div class="value">{{ number_format($transaction_count) }}</div>
        </div>
        <div class="summary-card">
            <h3>Avg Bags per Sale</h3>
            <div class="value">{{ $transaction_count > 0 ? number_format($total_bags / $transaction_count, 1) : '0' }}</div>
        </div>
    </div>

    <!-- Location Summary -->
    @if($location_summary && count($location_summary) > 0)
    <div class="section-title">Location Summary</div>
    <table>
        <thead>
            <tr>
                <th>Location</th>
                <th>Bag Types</th>
                <th>Total Bags</th>
                <th>Total Charges</th>
                <th>Transaction Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($location_summary as $location)
            <tr>
                <td>{{ $location['location'] }}</td>
                <td>{{ $location['bag_types'] ?? '' }}</td>
                <td class="text-center">{{ number_format($location['total_bags']) }}</td>
                <td class="text-right">${{ number_format($location['total_charges'], 2) }}</td>
                <td class="text-center">{{ number_format($location['transaction_count']) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- Transaction Details -->
    @if($transactions && count($transactions) > 0)
    <div class="section-title">Transaction Details</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Invoice No</th>
                <th>Location</th>
                <th>Bag Types</th>
                <th>Bags Sold</th>
                <th>Charges</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $transaction)
            <tr>
                <td>{{ $transaction->date }}</td>
                <td>{{ $transaction->invoice_no }}</td>
                <td>{{ $transaction->location }}</td>
                <td>{{ $transaction->bag_types ?? '' }}</td>
                <td class="text-center">{{ number_format($transaction->bags) }}</td>
                <td class="text-right">${{ number_format($transaction->charges, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>Report generated by IsleBooks POS System</p>
    </div>
</body>
</html>